<?php

namespace Docs\Swagger\Definitions;

class ClinicDefinition
{

/**
 * @SWG\Definition(
 *      definition="Clinic",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="small_description",
 *          description="small_description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="address",
 *          description="address",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="map_x",
 *          description="map_x",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="map_y",
 *          description="map_y",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="photo",
 *          description="photo",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="meta_keywords",
 *          description="meta_keywords",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="meta_description",
 *          description="meta_description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="status",
 *          description="status",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="facebook_title",
 *          description="facebook_title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="facebook_description",
 *          description="facebook_description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="facebook_image",
 *          description="facebook_image",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="twitter_title",
 *          description="twitter_title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="twitter_description",
 *          description="twitter_description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="twitter_image",
 *          description="twitter_image",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="image_title",
 *          description="image_title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="image_alt",
 *          description="image_alt",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="slug",
 *          description="slug",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="shortcut",
 *          description="shortcut",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="gallery",
 *          type="string",
 *          ref="#/definitions/Gallery"
 *      ),
 * )
 */

}
